[package]
name = "pets-citizens"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
serde = { version = "1.0.193", default-features = false, features = ["derive", "alloc"] }
csv = "1.3.0"
